modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU LGPL 3.0"
[[mods]]
modId = "emerald"
version = "${file.jarVersion}"
displayName = "Emerald"
logoFile="emerald_tablet.png"
authors = "DustW"
description = '''

'''
[[dependencies.emerald]]
modId = "forge"
mandatory = true
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.emerald]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
